# Generated by Django 5.2 on 2026-06-05 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('demandes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropositionCreneau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_proposee', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('duree_heures', models.PositiveSmallIntegerField(default=1)),
                ('salle', models.CharField(max_length=50)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propositions_creneaux', to='demandes.demande')),
                ('encadreur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profilencadreur')),
            ],
            options={
                'ordering': ['date_proposee', 'heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='Soutenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_proposee', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('salle', models.CharField(max_length=50)),
                ('duree_heures', models.PositiveSmallIntegerField(default=1)),
                ('statut', models.CharField(choices=[('proposee', 'Proposée'), ('validee', 'Validée'), ('annulee', 'Annulée')], default='proposee', max_length=20)),
                ('pv_url', models.URLField(blank=True, null=True)),
                ('mention_provisoire', models.TextField(blank=True, null=True)),
                ('demande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='soutenance', to='demandes.demande')),
                ('validee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='soutenances_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_proposee', 'heure_debut'],
            },
        ),
        migrations.CreateModel(
            name='Jury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_jury', models.CharField(choices=[('president', 'Président'), ('rapporteur', 'Rapporteur'), ('examinateur', 'Examinateur')], max_length=30)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profilencadreur')),
                ('soutenance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membres', to='soutenances.soutenance')),
            ],
            options={
                'unique_together': {('soutenance', 'enseignant', 'role_jury')},
            },
        ),
    ]
