# Generated by Django 6.0.7 on 2026-07-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilencadreur',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos_profil/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='profilencadreur',
            name='quota_max',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='profilencadreur',
            name='telephone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profiletudiant',
            name='adresse',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profiletudiant',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos_profil/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='profiletudiant',
            name='telephone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
