# Generated by Django 6.0.7 on 2026-07-14 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_utilisateur', models.CharField(blank=True, max_length=20)),
                ('action', models.CharField(max_length=255)),
                ('methode', models.CharField(blank=True, max_length=10)),
                ('chemin', models.CharField(blank=True, max_length=500)),
                ('statut_code', models.PositiveIntegerField(blank=True, null=True)),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('niveau', models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('security', 'Sécurité')], default='info', max_length=20)),
                ('details', models.TextField(blank=True)),
                ('horodatage', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_audit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-horodatage'],
                'indexes': [models.Index(fields=['-horodatage'], name='audit_audit_horodat_b48440_idx'), models.Index(fields=['utilisateur'], name='audit_audit_utilisa_a45ba1_idx'), models.Index(fields=['niveau'], name='audit_audit_niveau_ff84d3_idx')],
            },
        ),
    ]
