# Generated by Django 5.2 on 2026-06-05 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.TextField()),
                ('entreprise', models.CharField(blank=True, max_length=200)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('refusee', 'Refusée')], default='en_attente', max_length=20)),
                ('commentaire_encadreur', models.TextField(blank=True)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_reponse', models.DateTimeField(blank=True, null=True)),
                ('encadreur_effectif', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_effectives', to='accounts.profilencadreur')),
                ('encadreur_souhaite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_souhaitees', to='accounts.profilencadreur')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='accounts.profiletudiant')),
            ],
            options={
                'ordering': ['-date_soumission'],
                'permissions': [('view_own_demande', 'Peut voir ses propres demandes'), ('change_own_demande', 'Peut modifier sa demande avant acceptation'), ('view_demande_souhaitee', 'Peut voir les demandes où il est encadreur souhaité')],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('version', models.PositiveIntegerField(default=1)),
                ('type_doc', models.CharField(choices=[('brouillon', 'Brouillon'), ('final', 'Version finale'), ('rapport_stage', 'Rapport de stage'), ('autre', 'Autre')], max_length=30)),
                ('date_depot', models.DateTimeField(auto_now_add=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='demandes.demande')),
            ],
            options={
                'ordering': ['-version'],
                'unique_together': {('demande', 'version')},
            },
        ),
    ]
