# Generated by Django 6.0.7 on 2026-07-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='archivee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demande',
            name='date_validation_finale',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='eligible_soutenance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demande',
            name='entreprise_ville',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='demande',
            name='maitre_stage_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='demande',
            name='maitre_stage_nom',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='demande',
            name='reaffectee_par_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='commentaire_encadreur',
            field=models.TextField(blank=True),
        ),
    ]
